# 指定库的运行平台
DEVICETYPE=EM_EC_6230

# Add cpu kinds to CFLAGS
ifeq ($(DEVICETYPE),EM_EC4212_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC4212v3_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC4216_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC4216E_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC4217_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC4218_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_ERTU5100_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_ERTU5100W_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_CDHTW01_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_KYLAND_32AI)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_PDM_24AI)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_ERTU5108_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_ERTU5200_PD)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_DAC_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_CDHDR_ODM)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_LSZL_ODM)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_ADC_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EPSD9X5_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EW322_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_HIGHTIMER_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EW3XX_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_HIGHTIMER_LIB=y
#
else ifeq ($(DEVICETYPE),EM_FDA54_ODM)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_HIGHTIMER_LIB=y
#
else ifeq ($(DEVICETYPE),EM_HB54YZ_ODM)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_HIGHTIMER_LIB=y
#
else ifeq ($(DEVICETYPE),EM_TIANYBD_ODM)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ADC_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_ENGPIO_LIB=y
#
else ifeq ($(DEVICETYPE),EM_CSDTXY_ODM)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ADC_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_ENGPIO_LIB=y
#
else ifeq ($(DEVICETYPE),EM_BJHTFD_ODM)
CPUARCH=AT91SAM9G45
CFG_USART_LIB=y
CFG_ADC_LIB=y
CFG_ENGPIO_LIB=y
CFG_DAC_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_KBD_LIB=y
#
else ifeq ($(DEVICETYPE),EM_BJZTXY_ODM)
CPUARCH=AT91SAM9G45
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
CFG_KBD_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC2012)
CPUARCH=AT91SAM9G20
CFG_USART_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_GPIO_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC4210)
CPUARCH=AT91SAM9G20
CFG_USART_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_GPIO_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC2212_EX)
CPUARCH=AT91SAM9G20
CFG_USART_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_GPIO_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_BJTKY_ODM)
CPUARCH=AT91SAM9263
CFG_USART_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_GPIO_LIB=y
CFG_ENGPIO_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_BEIJZJ_ODM)
CPUARCH=AT91SAM9G20
CFG_USART_LIB=y
CFG_ADC_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
else ifeq ($(DEVICETYPE),EM_BEIJQL_ODM)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_BEIJHL_ODM)
CPUARCH=AT91SAM9G45
CFG_USART_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EU_6016)
CPUARCH=AT91SAM9G45
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_SOM9G45_PD)
CPUARCH=AT91SAM9G45
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC2022E_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EIA410_PD)
CPUARCH=AT91SAM9X5
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_LTC_2016)
CPUARCH=LOONGSON1B
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_8310)
CPUARCH=MPC8315E
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_HR405)
CPUARCH=AMCC405EP
CFG_USART_LIB=y
 #CFG_FIFO_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_6012)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_6210)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_6510)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_6018)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_6230)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EU_6200)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_TJMLODM)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_EC_TJMLPOS)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_ZSK_ODM)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_JBH_ODM)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_DTXY_A8GATE)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_ZHHR_A8GATE)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_BJPRT_ODM)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else ifeq ($(DEVICETYPE),EM_WXS_A8GATE)
CPUARCH=TIAM335X
CFG_USART_LIB=y
CFG_ENGPIO_LIB=y
CFG_GPIO_LIB=y
CFG_DATETIM_LIB=y
CFG_TIMER_LIB=y
CFG_HIGHTIMER_LIB=y
CFG_WDG_LIB=y
CFG_MISCS_LIB=y
#
else
# 自定义库的支持类型（若不需要包含相应函数，则#注释该选项）
# 平台的CPU类型
CPUARCH = AT91SAM9G20
#串口操作支持函数
CFG_USART_LIB=y
#ADC操作支持函数
CFG_ADC_LIB=y
#用户层IO操作支持函数
CFG_GPIO_LIB=y
#DAC操作支持函数
CFG_DAC_LIB=y
#GPIO端口高级操作相关函数
CFG_ENGPIO_LIB=y
#总线端口操作支持函数
CFG_PORT_LIB=y
#日期/时间操作支持函数
CFG_DATETIM_LIB=y
#定时器操作支持函数
CFG_TIMER_LIB=y
#高精度定时器操作支持函数
CFG_HIGHTIMER_LIB=y
#看门狗操作支持函数
CFG_WDG_LIB=y
#蜂鸣器和指示灯操作支持函数
CFG_MISCS_LIB=y
#库包含自定义键盘操作支持函数
CFG_KBD_LIB=y	
endif

# 指定库名称
LIBSNAME = EM_Middleware_Lib
